getsentry/sentry-javascript-bundler-plugins

.github/workflows/checks.yml, packages/unplugin/src/getReleaseName.ts, packages/unplugin/src/index.ts, packages/unplugin/test/getReleaseName.test.ts
relates: #20  
This behaviour tries to replicate the behaviour of release option of sentry-webpack-plugin.
Release name can be specified via process.env.SENTRY_RELEASE. Otherwise, it will automatically detects values for Heroku, AWS CodeBuild, CircleCI and Vercel. Otherwise uses HEAD's commit SHA. (For HEAD option, requires access to git CLI and for the root directory to be a valid repository).
Logic taken from [sentry-cli here](https://github.com/getsentry/sentry-cli/blob/master/src/utils/releases.rs#L87-L143)
=> chore: add release discovery

packages/playground/build-webpack4.js, packages/playground/config.json, packages/playground/package.json, packages/playground/src/smallNodeApp.js, packages/playground/vite.config.smallNodeApp.js, packages/unplugin/rollup.config.js, packages/unplugin/src/cli.ts, packages/unplugin/src/facade.ts, packages/unplugin/src/index.ts, packages/unplugin/src/types.ts, yarn.lock
* make Sentry CLI calls
* adds default options
* add small node sample app to test sourcemaps upload
=> feat(sourcemaps): Add basic source maps upload functionality

.github/workflows/checks.yml, packages/integration-tests/.eslintrc.js, packages/integration-tests/.gitignore, packages/integration-tests/README.md, packages/integration-tests/fixtures/basic-release-injection/basic-release-injection.test.ts, packages/integration-tests/fixtures/basic-release-injection/input/entrypoint.js, packages/integration-tests/fixtures/basic-release-injection/setup.ts, packages/integration-tests/jest.config.js, packages/integration-tests/package.json, packages/integration-tests/scripts/run-fixture-setups.ts, packages/integration-tests/tsconfig.json, packages/integration-tests/utils/create-cjs-bundles.ts, packages/playground/build-esbuild.js, packages/playground/build-webpack4.js, packages/unplugin/test/example.test.ts, yarn.lock
Adds initial setup for integration tests and a test case to test basic release injection.
=> test(integration-tests): Add integration test scaffolding and release injection integration test

packages/playground/vite.config.smallNodeApp.js, packages/unplugin/package.json, packages/unplugin/src/index.ts, packages/unplugin/src/sentry/api.ts, packages/unplugin/src/sentry/cli.ts, packages/unplugin/src/sentry/facade.ts, yarn.lock
This PR replaces the "create release" sentry-cli call with our own implementation. Since it is the first call, I set up a pretty basic `api.ts` file which has some internal functions to make the actual API requests. Happy to revisit this or replace it w/ something more sophisticated later on (or if requested by reviewers). 
Also adds axios as a dependency.
=> feature(sourcemaps): Replace "create release" command

packages/playground/vite.config.smallNodeApp.js, packages/unplugin/package.json, packages/unplugin/rollup.config.js, packages/unplugin/src/index.ts, packages/unplugin/src/sentry/api.ts, packages/unplugin/src/sentry/facade.ts, packages/unplugin/src/sentry/sourcemaps.ts, packages/unplugin/src/types.ts
This PR adds a very(!) basic sourcemap upload functionality:
- per-file based sourcemaps upload (not chunked)
- no sourcemaps preprocessing
=> feat(sourcemaps): replace sourcemaps cli upload

packages/unplugin/package.json, packages/unplugin/src/index.ts, packages/unplugin/src/sentry/api.ts, packages/unplugin/src/sentry/facade.ts, packages/unplugin/src/sentry/telemetry.ts, packages/unplugin/src/types.ts, yarn.lock
This PR adds Sentry integration to sentry-unplugin.
This will allow us to proactively monitor and get alerted about our customers errors.
_Side note so I don't forget:
I would have expected to get distributed tracing when making requests to sentry API as we are sending `sentry-trace`. Let's discuss why this could happen. Different org maybe?_
=> feat: Add Sentry

packages/unplugin/src/index.ts, packages/unplugin/src/sentry/releasePipeline.ts, packages/unplugin/src/sentry/telemetry.ts, packages/unplugin/src/types.ts
This PR removes our `SentryFacade` abstraction from the project. As we got rid of Sentry CLI (#34) there is no need anymore to have this additional layer and we can just call the facade's functions directly.
Additionally, the PR introduces the `SentryContext` type which should hold "sentry internal" values/data, like the hub and the parent span. We might wanna add the logger here later (cc @vladanpaunovic). This replaces the arguments we pass down to the release pipeline functions so we can add more stuff w/o having to add yet another param.
=> ref: remove sentryFacade

packages/unplugin/src/index.ts, packages/unplugin/src/sentry/logger.ts, packages/unplugin/src/types.ts, packages/unplugin/test/logger.test.ts
Just some opinionated cleaning up of the logger (reducing API surface, minor naming changes, test cleanup, and so forth).
Some changes are objective though:
- We call `console.log` instead of `console.warn` and `console.error`. Reason is that `.warn` is just an alias for `.error` and `.error` writes to stderr instead of stdout and we don't want that.
- Don't expose `prefix` on logger - it's unnecessary.
- Instead of prefixing with `[Sentry-unplugin]` we're now prefixing with `[sentry-{insert bundler here}-plugin]`.
=> ref(unplugin): Clean up logger

README.md, packages/esbuild-plugin/README.md, packages/rollup-plugin/README.md, packages/unplugin/README.md, packages/vite-plugin/README.md, packages/webpack-plugin/README.md
This updates and adds `README.md` files across the packages we want to release.
- removes old `hackweek-sentry-unplugin` links
- makes warnings that this is a heavy WIP more explicit
- adds Readme to the core sentry-unplugin package
=> chore: Update READMEs

CHANGELOG.md
This adds an almost empty `CHANGELOG.md` file to the repo. I created an initial (yet unreleased) release to have at least something there. Other than that this is a plain copy from the [JS SDK repo's changelog](https://github.com/getsentry/sentry-javascript/blob/052aa6b0fa551aacdc1318494f7eeaf7b53f2e1f/CHANGELOG.md#L1). 
Not sure yet what's gonna go into the first release or when/how that happens so we might need an additional PR for that when we get to it.
=> chore: Add CHANGELOG.md file

lerna.json, package.json, packages/esbuild-plugin/package.json, packages/eslint-configs/package.json, packages/integration-tests/package.json, packages/playground/package.json, packages/rollup-plugin/package.json, packages/tsconfigs/package.json, packages/unplugin/package.json, packages/vite-plugin/package.json, packages/webpack-plugin/package.json, scripts/craft-pre-release.sh, yarn.lock
This PR (unfortunately) adds lerna to our repo to use it as a mechanism of bumping all our package versions. We need this for the craft publishing process.
For future readers, here are some reasons for choosing lerna:
- Nx doesn't have a version bump command built in :(
- I tried to use the Nx [semVer](https://www.npmjs.com/package/@jscutlery/semver) plugin but this tool does too much for our purposes
- it creates git tags (can't disable this)
- it automatically determines if the version should be a major/minor/patch bump
- we could only manually override the decision to bump to the next major/minor/patch but we can't just specify a version. 
-  Because of these limitations and for time reasons we chose not to pursue this approach further
- I tried to use `yarn version` but this would …
=> feat(publish): Add version bump script

.craft.yml, .github/workflows/checks.yml, .github/workflows/release.yml
This adds a few files to set up Craft and our release process.
Draft for testing purposes
=> feat(publish): Add GHA and Craft configs

.craft.yml, CHANGELOG.md
Fixes a regex typo in the `requireNames` attribute. Updates Changelog version (0.0.0 is the base tag now)
=> fix(publish): Correct craft requireNames config

.craft.yml
This adjusts the repo name in `.craft.yml` to the current (and hopefully final) repo name. Hopefully fixes the GH [asset uploading issue](https://github.com/getsentry/publish/actions/runs/3295724144/jobs/5434563208)  from the last craft run.
=> fix(publish): Rename repo in craft config

package.json, packages/bundler-plugin-core/package.json
After our initial package release I noticed that the NPM page of the `@sentry/bundler-plugin-core` package still pointed to the old `getsentry/sentry-unplugin` repo. This PR updates two `package.json`s that still had outdated `repository` and `homepage` values.
=> fix(publish): Fix repository and homepage values in root package.json

packages/bundler-plugin-core/package.json, packages/bundler-plugin-core/src/index.ts, yarn.lock
Replaces usage of the `buildEnd` hook with usage of the `writeBundle` hook. The `buildEnd` hook only runs before bundles have been written to disk and that is too early for sourcemaps upload - the `writeBundle` hook runs late enough.
=> fix: Use `writeBundle` hook instead of `buildEnd`

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/bundler-plugin-core/src/types.ts, packages/integration-tests/fixtures/array-entries-option/setup.ts, packages/integration-tests/fixtures/basic-release-injection/setup.ts, packages/integration-tests/fixtures/function-entries-option/setup.ts, packages/integration-tests/fixtures/regex-entries-option/setup.ts, packages/integration-tests/fixtures/string-entries-option/setup.ts, packages/integration-tests/utils/create-cjs-bundles.ts
This adds all options + JSDoc from the webpack plugin to our `Options` type. 
Some things in this PR we can discuss before merging, e.g. what to do with the `process.env` thing or if we can get rid of the `configFile` option (which I'd vote yes on). 
Others (e.g. `customHeaders` vs `customHeader`), I'd like to tackle in a follow-up PR as it involves modifying more code than just changing the type. 
ref: #62
=> Add all options including JSDoc to `Options` type

MIGRATION.md
This adds a `MIGRATION.md` file to our repo to add breaking changes to. I added the two breaking changes we discussed in #66 as a start. We can iterate on this document and adjust/add changes as we progress towards replacing the webpack plugin.
=> chore: Add MIGRATION.md guide

packages/bundler-plugin-core/package.json, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/sentry/api.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/bundler-plugin-core/src/sentry/sourcemaps.ts, yarn.lock
Ref: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/62
This PR adds the logic to grab files the user configured via `include` and `paths` and applies logic for the correct release artifact prefixes:
- If the user points `paths` to a file, it's artifact path will be its basename prefixed with the `urlPrefix` (eg. `/foo/bar/baz.js` -> `~/baz.js`)
- If the user points `paths` to a directory, the plugin will include all the files recursively included in that directory. The file's artifact paths will be the file path, but the part that the user provided via `paths` is replaced with the `urlPrefix`.
We also filter based on file extensions with the `ext` option.
=> feat: Implement `paths` and `ext` options for `include`

.github/workflows/checks.yml
Just saw that we still have this TODO here
=> chore(ci): Only upload artifacts on release branches

packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/sentry/api.ts, packages/bundler-plugin-core/src/sentry/sourcemaps.ts, packages/bundler-plugin-core/test/option-mappings.test.ts
This PR adds the `ignore` option implementation to the plugin core. We're using `glob` for recursively searching for files which, as luck would have it, also supports an `ignore` option (h/t @lforst for finding this out). 
We don't have to do a lot to get it working properly other than converting the ignore entries from our users to absolute paths. I tried passing on relative paths but it wouldn't work as expected when trying to replicate how users (and our [documentation](https://github.com/getsentry/sentry-webpack-plugin#optionsinclude)) [use the `ignore` option](https://cs.github.com/?scopeName=All+repos&scope=&q=%22new+sentrycliplugin%28%22+ignore). 
Side note: I decided to split this and the `ignoreFile` options up into separate PRs as the latter one requires some additional work and …
=> feat(core): Add `ignore` option

packages/bundler-plugin-core/package.json, packages/bundler-plugin-core/src/sentry/sourcemaps.ts, packages/playground/.sentryignore, packages/playground/vite.config.smallNodeApp.js, yarn.lock
This PR implements the `ignoreFile` option and rewrites the `ignore` option behaviour. Previously, we used `glob`'s `ignore` option to pass an array of ignore rules to the library. This meant we'd get back a set of filtered files where ignore rules were already applied. However, `glob` does not support negated ignore rules, meaning ignore patterns like "ignore everything except file x" wouldn't work. 
With this PR, we introduce a new library to the project: [ignore](https://www.npmjs.com/package/ignore). It lets us add rules to a rule checker (regardless of if these rules come from a file or an array). We now first collect all files with `glob` and subsequently filter out the ones that are ignored by the specified ignore rules. This rule checker supports all rules as specified in …
=> feat(core): Add `ignoreFile` option

packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/sentry/api.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/bundler-plugin-core/src/types.ts, packages/bundler-plugin-core/test/option-mappings.test.ts
Rename `customHeaders` to `customHeader` and change user-facing data type to string. This change aligns the option with the Sentry Webpack Plugin.
Note: For internal usage, I left it as `Record<string, string>` because it makes it easier for us to work with. We might consider merging other Http headers into this property in the future. For instance authToken and UserAgent. Then we'd have one internal option (e.g. `headers`) that we could populate during the internal option conversion. 
fixes #83
=> ref(core): Change customHeaders option to customHeader

packages/bundler-plugin-core/package.json, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/sentry/cli.ts, packages/bundler-plugin-core/src/sentry/logger.ts, packages/bundler-plugin-core/src/types.ts, packages/bundler-plugin-core/test/cli.test.ts, packages/bundler-plugin-core/test/logger.test.ts, yarn.lock
This PR brings back Sentry CLI as a dependency and it adjusts a few necessary things to be compatible with the CLI along the way:
* Add CLI dependency
* Add `getCLI()` function which creates a CLI or a stub if in `dryRun` mode
* Adjust logger (+ introduce a debug level)
* dryrun mode of CLI needs it 
* added variable args parameter to fully utilize `console.log` capabilities
* Bring back the `configFile` option as it is relevant again because of Sentry CLI
ref #85
=> ref(core): Add Sentry CLI

packages/bundler-plugin-core/src/sentry/api.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/integration-tests/fixtures/array-entries-option/setup.ts, packages/integration-tests/fixtures/basic-release-injection/setup.ts, packages/integration-tests/fixtures/function-entries-option/setup.ts, packages/integration-tests/fixtures/regex-entries-option/setup.ts, packages/integration-tests/fixtures/string-entries-option/setup.ts
This replaces our own release finalization logic with Sentry CLI's implementation
RIP
Note: Since integration tests were failing because the CLI expects parameters that we didn't specify, I opted to set the `dryRun` option in our test setups. We're only testing release injection in these tests, so apart from the CLI's version detection (which still works as expected in dry run mode) we don't need any of its functionality.
ref #85
=> ref(core): Use Sentry-CLI to finalize release

packages/bundler-plugin-core/src/sentry/api.ts, packages/bundler-plugin-core/src/sentry/cli.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts
Replace previous custom implementation with Sentry CLI logic analogously to the [webpack plugin](https://github.com/getsentry/sentry-webpack-plugin/blob/137503f3ac6fe423b16c5c50379859c86e689017/src/index.js#L487-L490)
ref: #85
=> ref(core): Use Sentry CLI for artifact deletion

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/bundler-plugin-core/src/types.ts, packages/bundler-plugin-core/test/releasePipeline.test.ts, packages/playground/vite.config.smallNodeApp.js
This PR adds the implementation of the `deploy` option and its step in the release pipeline. The implementation is mostly taken from the [webpack plugin](https://github.com/getsentry/sentry-webpack-plugin/blob/137503f3ac6fe423b16c5c50379859c86e689017/src/index.js#L524-L536) and relies on Sentry CLI.
fixes #95
=> feat(core): Add `deploy` command

packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/sentry/cli.ts, packages/bundler-plugin-core/test/option-mappings.test.ts
Previously, we coverted the user-facing `customHeader` option, typed as string to an internal option typed `Record<string, string>`. This was handy for adding the header to our outgoing API requests. Since we don't do these ourselves anymore but rely on Sentry CLI, it's just easier to pass this option through to the CLI which also expects the string representation.
ref: #91
=> ref(core): Remove customHeader conversion in internal options

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/sentry/cli.ts, packages/bundler-plugin-core/src/sentry/logger.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/bundler-plugin-core/src/types.ts, packages/bundler-plugin-core/test/logger.test.ts, packages/bundler-plugin-core/test/option-mappings.test.ts
This PR revisits our options after checking them for completeness against the webpack plugin and Sentry CLI: 
* Add the missing `debug` options to the plugin and make the `logger.debug` output depend on it
* Pass the previously unused `dist` option to the CLI constructor
* Move the previously top-level `validate` option to `IncludeEntry`
ref #91
=> ref(core): Add missing and change unused options

MIGRATION.md, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/types.ts, packages/bundler-plugin-core/test/option-mappings.test.ts, packages/integration-tests/fixtures/releases-injection/input/entrypoint.js, packages/integration-tests/fixtures/releases-injection/releases-injection.test.ts, packages/integration-tests/fixtures/releases-injection/setup.ts
In our initial implementation of release injection, we did not inject the `SENTRY_RELEASES` global variable which was added to the webpack plugin in https://github.com/getsentry/sentry-webpack-plugin/pull/307. 
Although it is unlikely that people are actually using this feature, it doesn't hurt us a lot if we implement it to prevent breakage for anyone who might manually be relying on this variable (e.g. MFE projects). 
EDIT: We decided to make this behaviour opt-in by introducing a new `injectReleasesMap` option. 
---
A little more context:
The idea of this variable is to have a map of projects that point to the same release. This seems to be a request for module federation and MFEs where it seems that multiple projects want to access the same release.
This original PR was merged, …
=> feat(core): Add `SENTRY_RELEASES` variable during release injection

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/src/types.ts, packages/bundler-plugin-core/test/option-mappings.test.ts, packages/bundler-plugin-core/test/releasePipeline.test.ts, packages/playground/vite.config.smallNodeApp.js
This PR refactors the validation of the plugin options. Since Sentry CLI does most of the validation work out of the box, we only need to take care of a few special cases. Therefore:
* Deleted the ugly and duplicated org, project, auth, etc. checks in the release pipeline steps as most of them aren't necessary at all in that form
* Added a centralized validation function that validates certain combinations of options that Sentry CLI doesn't do (these validations are also present in the webpack plugin, albeit in a little different form)
* Added special validation of the `release` value as it simply has to be present to continue with release injection and the release creation pipeline
* All validation errors will cause the plugin to throw unless the user specified an error handler. Happy to …
=> ref(core): Refactor options validation

packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/test/option-mappings.test.ts
Closes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/106
Not 100% sure if the test is the "best", but couldn't think of a better way to test this easily. I'd say it is OK, but if you have another idea, I'm happy to change it.
=> feat: Use `SENTRY_HEADER` env var when available

packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/bundler-plugin-core/test/releasePipeline.test.ts
In our release creation pipeline, certain steps (`cleanArtifacts`, `setCommits`, `finalize`, `deploy`) can be skipped depending on the chosen options. In case they are skipped, as of this PR, we don't anymore create spans for these steps. 
This PR also adjusts release pipeline tests (and adds the steps that were previously missing)
ref #99
=> ref(core): Don't create spans for skipped release steps

packages/bundler-plugin-core/package.json, packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/test/sentry/cli.test.ts, packages/bundler-plugin-core/test/sentry/logger.test.ts, packages/bundler-plugin-core/test/sentry/releasePipeline.test.ts, packages/bundler-plugin-core/test/sentry/telemetry.test.ts, yarn.lock
This PR just removes a few dependencies we don't need anymore after switching back to Sentry CLI. 
I made a small adjustment to our `captureMinimalError` function which treated Axios errors differently from other errors (we could also see this as a first step for #99)
=> chore(core): Remove unused dependencies

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/test/sentry/telemetry.test.ts
This PR adds a subset of our plugin options as tags to Sentry events. Obviously, we cannot send all options but we have to be careful to only send insensitive data, such as if an optional step (e.g. `deploy`) was selected or not. 
Going forward, we can use this data to evaluate which options are used and for debugging issues. 
As suggested by @AbhiPrasad we're sending this data as tags rather than context.
This PR also adds some tests (thanks GH copilot for the help)
ref #99
=> feat(core): Add plugin options as tags

packages/esbuild-plugin/README.md, packages/rollup-plugin/README.md, packages/vite-plugin/README.md, packages/webpack-plugin/README.md
Resolves https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/114
Adds examples to the READMEs of the individual bundlers.
=> docs: Add examples to individual READMEs

packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/test/sentry/telemetry.test.ts
This tiny PR just adds another tag to Sentry events containing the used node version. This can help us with seeing in which node versions the plugins (and possibly their respective projects) are used.
ref #99
=> feat(core): Add node version tag

README.md, packages/bundler-plugin-core/README.md, packages/esbuild-plugin/README.md, packages/rollup-plugin/README.md, packages/vite-plugin/README.md, packages/webpack-plugin/README.md
Ref: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/50
Removes the "Work in progress" warnings from the package READMEs as we are approaching the first proper release of the plugins.
=> docs: Remove WIP warning from READMEs

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/sentry/logger.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/test/option-mappings.test.ts, packages/bundler-plugin-core/test/sentry/logger.test.ts, packages/bundler-plugin-core/test/sentry/releasePipeline.test.ts, packages/bundler-plugin-core/test/sentry/telemetry.test.ts
Fixes #129
- Introduces a custom transport that only sends telemetry events to our Sentry instance when Sentry CLI has determined that the target URL for the source maps is the Sentry SaaS URL. (this is due to PII reasons)
- Refactors usage of the telemetry option so we don't mutate it.
- Gets rid of manually mutating client options
- Reduces noise of log messages and breadcrumbs sent to our Sentry instance by not logging debug log statements - these are for our users to debug
=> fix(core): Fix telemetry option logic

.github/workflows/checks.yml, packages/bundler-plugin-core/src/index.ts, packages/e2e-tests/scenarios/basic-upload/config.ts, packages/e2e-tests/scenarios/basic-upload/setup.ts, packages/e2e-tests/scripts/run-scenario-setups.ts, packages/integration-tests/fixtures/array-entries-option/array-entries-option.test.ts, packages/integration-tests/fixtures/array-entries-option/setup.ts, packages/integration-tests/fixtures/basic-release-injection/basic-release-injection.test.ts, packages/integration-tests/fixtures/basic-release-injection/setup.ts, packages/integration-tests/fixtures/function-entries-option/function-entries-option.test.ts, packages/integration-tests/fixtures/function-entries-option/setup.ts, packages/integration-tests/fixtures/regex-entries-option/setup.ts, packages/integration-tests/fixtures/regex-entries-option/string-entries-option.test.ts, packages/integration-tests/fixtures/releases-injection/releases-injection.test.ts, packages/integration-tests/fixtures/releases-injection/setup.ts, packages/integration-tests/fixtures/string-entries-option/setup.ts, packages/integration-tests/fixtures/string-entries-option/string-entries-option.test.ts, packages/integration-tests/scripts/run-fixture-setups.ts, packages/integration-tests/utils/create-cjs-bundles.ts, packages/integration-tests/utils/testIf.ts, packages/playground/build-webpack4.js, packages/playground/build-webpack5.js, packages/playground/scripts/request-logger-proxy.ts, packages/playground/vite.config.js, packages/playground/vite.config.smallNodeApp.js
Adds a test matrix in our integration test CI for Node.js versions and Linux + Windows. We currently skip versions 10 and 12 because they cause issues with our dev-dependencies - which I believe covers the 80% use-case.
=> ci(integration-tests): Add OS and Node.js version matrix

packages/bundler-plugin-core/src/sentry/telemetry.ts
`server_name` might contain sensitive data so we shouldn't send it in telemetry events.
=> feat(core): Remove `server_name` from telemetry events

packages/bundler-plugin-core/src/sentry/releasePipeline.ts
This PR fixes telemetry by finishing spans after CLI commands fail.
=> fix(core): Finish spans when CLI commands fail

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/test/sentry/telemetry.test.ts
Stack traces might contain PII. We can just remove the entire stack trace instead of renaming the frames because once we get rid of the frames the stack trace becomes useless anyways.
=> ref(core): Don't record stack traces for telemetry

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/sentry/logger.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/bundler-plugin-core/test/sentry/logger.test.ts, packages/bundler-plugin-core/test/sentry/releasePipeline.test.ts
Breadcrumbs can potentially leak PII so we make their usage explicit.
=> ref(core): Decouple breadcrumb usage from logger

CHANGELOG.md, packages/bundler-plugin-core/package.json, packages/esbuild-plugin/package.json, packages/rollup-plugin/package.json, packages/vite-plugin/package.json, packages/webpack-plugin/package.json
Fixes #140
This PR adds definitions to the `package.json`s of published packages and changes the file extension of the ESM bundle to `.mjs` which should fix importing the bundler plugins when using `"type": "module"` or `--experimental-modules`.
=> fix: Add definitions in `package.json` for ESM resolution

packages/bundler-plugin-core/src/index.ts
Fixes #142
By injecting an `import` statement into CJS files we're accidentally tricking Vite/Rollup into thinking that these files are ESM and that messes up the exports (i.e. `module.exports`).
As an intermediary heuristic, we will not inject the release module in any files within a `node_modules` folder. This should unblock a good chunk of people but I am somewhat expecting this to still be a problem if people are bundling CJS code.
=> fix: Exclude `node_modules` from release injection

.github/workflows/checks.yml
We don't wanna run E2E tests for forks or dependabot because they don't have an API token configured and will always fail.
=> ci: Don't run E2E tests for forks

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts
Sends the user project as `dist` in telemetry so we can query for it efficiently in dashboards since `dist` is an indexed parameter.
=> ref(core): Send project as `dist` in telemetry

packages/bundler-plugin-core/package.json, yarn.lock
This PR bumps unplugin to the newest version. Even though it is a major it shouldn't have any breaking changes it is just to mark it as stable.
=> deps(core): Bump unplugin version

MIGRATION.md, packages/e2e-tests/utils/create-cjs-bundles.ts, packages/esbuild-plugin/README.md, packages/esbuild-plugin/src/index.ts, packages/esbuild-plugin/test/public-api.test.ts, packages/rollup-plugin/README.md, packages/rollup-plugin/src/index.ts, packages/rollup-plugin/test/public-api.test.ts, packages/vite-plugin/README.md, packages/vite-plugin/src/index.ts, packages/vite-plugin/test/public-api.test.ts, packages/webpack-plugin/README.md, packages/webpack-plugin/src/index.ts, packages/webpack-plugin/test/public-api.test.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/161
Turns all the default exports of the plugins into named exports. This is just way more future proof in case we want to export more stuff and properly support CJS at the same time.
=> ref: Turn default exports into named exports

MIGRATION.md, packages/bundler-plugin-core/src/index.ts, packages/esbuild-plugin/src/index.ts, packages/rollup-plugin/src/index.ts, packages/vite-plugin/src/index.ts, packages/webpack-plugin/src/index.ts
This PR adds a function which exists in the current implementation of the webpack plugin to check for the existence of the sentry cli in node modules.
We need this for the Next.js SDK.
=> feat: Add `sentryCliBinaryExists` function

packages/vite-plugin/README.md
see changelog from 0.3.0 to 0.4.0
=> docs: Fix documentation to use named exports

packages/bundler-plugin-core/src/index.ts
Hopefully fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/194
It seems like injecting into 3rd party modules may cause them to be bundled/resolved differently and this will fail some builds.
It could be that this is just an incompatibility with another plugin but I say it is worth just making this exemption.
=> fix(core): Skip all transformations for 3rd party modules

packages/bundler-plugin-core/package.json, packages/bundler-plugin-core/src/debug-id.ts, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/types.ts, yarn.lock
Ref: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/191
Similar to https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/192, we now add debug ID injection to the Webpack plugin.
Note this needs tests. We will add them as a follow-up when we identified some quirks with the injection across all bundlers.
=> feat(webpack): Add debug ID injection to the webpack plugin

packages/bundler-plugin-core/src/index.ts
Don't try to upload artifacts and/or create releases when in watch mode. Release injection can still happen regardless.
=> ref(core): Don't interact with Sentry in watch-mode

packages/bundler-plugin-core/src/index.ts
sentry-release-injection-file is coming from node_modules so you have to include that before you exclude node_modules.
=> fix(core): Don't exclude release injection module

CHANGELOG.md, packages/bundler-plugin-core/package.json, packages/esbuild-plugin/package.json, packages/rollup-plugin/package.json, packages/vite-plugin/package.json, packages/webpack-plugin/package.json
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/183
=> fix: Add typing exports to packages

CHANGELOG.md, packages/bundler-plugin-core/src/index.ts
=> fix(core): Fix vite complaining about CJS import of `webpack-sources`

packages/bundler-plugin-core/rollup.config.js, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/tsconfig.json
fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/211
Rollup takes care of correctly transpiling the import meta stuff
=> fix(core): Use `createRequire` to not use built-in `require` in ESM

packages/bundler-plugin-core/src/types.ts
Ref: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/215
This just adds a type that reflects everything in [Sentry RFC 0086](https://github.com/getsentry/rfcs/blob/main/text/0086-sentry-bundler-plugins-api.md).
=> ref(core): Add new options type for future use

.github/workflows/checks.yml
The switch to the newer artifact bundle upload has rendered our e2e tests faulty because the endpoint we ping to check for uploaded source maps doesn't return them anymore.
For now we disable them so we can have green CI again.
=> test: Disable E2E tests

packages/bundler-plugin-core/package.json, packages/bundler-plugin-core/rollup.config.js, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/sentry/releasePipeline.ts, packages/bundler-plugin-core/src/types.ts, packages/esbuild-plugin/package.json, packages/esbuild-plugin/rollup.config.js, packages/playground/package.json, packages/rollup-plugin/package.json, packages/rollup-plugin/rollup.config.js, packages/vite-plugin/package.json, packages/vite-plugin/rollup.config.js, packages/webpack-plugin/package.json, packages/webpack-plugin/rollup.config.js, yarn.lock
Clean up rollup configs, bump Sentry SDK, and don't bundle parts of the SDK anymore.
=> build: Clean up rollup configs

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/plugins/debug-id-upload.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/src/types.ts
=> feat(core): Add `deleteFilesAfterUpload` option

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/plugins/debug-id-upload.ts, packages/bundler-plugin-core/src/types.ts
Adds the `rewriteSources` hook to the plugin which allows to modify the names of files inside the stacktrace on Sentry.
The hook is called for each individual source file and also passed the entire source map object for convenience.
The default logic if not otherwise defined is to make all the sources relative to `process.cwd()` or to strip away a protocol if there is one (this is mainly for webpack).
=> feat(core): Implements rewrite sources for debug ID upload

packages/bundler-plugin-core/src/plugins/debug-id-upload.ts
Uses debug ID as filename for upload which should make it easier to troubleshoot.
Also changes the log level of a particular log message that is potentially a bit spammy.
=> ref(core): Use debug ID as filename for upload

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/plugins/debug-id-upload.ts, packages/integration-tests/fixtures/build-information-injection/setup.ts, packages/playground/build-esbuild.js, packages/playground/build-webpack4.js, packages/playground/build-webpack5.js, packages/playground/config.json, packages/playground/rollup.config.mjs, packages/playground/vite.config.js
Fixes a bug where Sentry CLI throws if we only pass an empty string as a release value for debug ID upload.
=> fix(core): Account for undefined release name values

packages/dev-utils/src/generate-documentation-table.ts
Npm transforms anchor tags in a way that destroys the links if you don't put them inside a heading like this.
=> docs: Fix anchor tags in READMEs

packages/bundler-plugin-core/src/plugins/telemetry.ts
Ref: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/264
=> fix: Don't show log message if telemetry is disabled

packages/bundler-plugin-core/src/debug-id-upload.ts, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/types.ts, packages/dev-utils/src/generate-documentation-table.ts, packages/esbuild-plugin/README_TEMPLATE.md, packages/esbuild-plugin/src/index.ts, packages/playground/build-esbuild.js, packages/playground/build-webpack4.js, packages/playground/build-webpack5.js, packages/playground/rollup.config.mjs, packages/playground/vite.config.js, packages/rollup-plugin/README_TEMPLATE.md, packages/rollup-plugin/src/index.ts, packages/vite-plugin/README_TEMPLATE.md, packages/vite-plugin/src/index.ts, packages/webpack-plugin/README_TEMPLATE.md, packages/webpack-plugin/src/index.ts
Will auto detect build artifacts based on the information bundlers provide in the build end hooks - making the `assets` option optional.
Risky change incoming.
=> feat: Auto detect build artifacts

packages/bundler-plugin-core/src/debug-id-upload.ts
Will help people understand a potential cause for sources not being found.
A better approach for the futre is to detect whether they have enabled it via the options.
=> ref: Improve log message when sourcemap cannot be found

packages/bundler-plugin-core/src/index.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/288
Like we did in the old webpack plugin: https://github.com/getsentry/sentry-webpack-plugin/blob/3628137a10c93e0bf8f8362abc19c0b4c46218ca/src/index.js#L12
=> feat(core): Set custom user agent when interacting with Sentry

packages/bundler-plugin-core/src/debug-id-upload.ts
The results from `glob()` are not guarenteed to be ordered, and prevent deterministic output.
This manifests in the assignment of artefeact names, as well as the bundle-id.
=> feat: Sort globbed files to ensure deterministic bundle IDs

packages/bundler-plugin-core/src/options-mapping.ts
Resolves https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/316
I think we accidentally removed this functionality.
=> fix: Use `SENTRY_RELEASE` environment variable to set `release.name` option

packages/bundler-plugin-core/src/index.ts, packages/esbuild-plugin/src/index.ts, packages/integration-tests/fixtures/basic-release-injection/setup.ts, packages/integration-tests/fixtures/disabled-release-injection/setup.ts, packages/integration-tests/fixtures/dont-mess-up-user-code/dont-mess-up-user-code.test.ts, packages/integration-tests/fixtures/dont-mess-up-user-code/input/import.js, packages/integration-tests/fixtures/dont-mess-up-user-code/input/index.js, packages/integration-tests/fixtures/dont-mess-up-user-code/setup.ts
Adds a suffix to the entrypoint resolver so that esbuild knows our proxy module is something different from the actual entrypoint when resolving the actual entrypoint through our proxy module.
Complicated. I know...
Also adds a test to ensure we don't completely fuck up user code like we did here.
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/319
=> fix(esbuild): Don't override user code with proxy module

packages/bundler-plugin-core/src/utils.ts, packages/bundler-plugin-core/test/utils.test.ts, packages/esbuild-plugin/src/index.ts, packages/integration-tests/fixtures/debug-id-injection/debug-id-injection.test.ts, packages/integration-tests/fixtures/debug-id-injection/input/bundle1.js, packages/integration-tests/fixtures/debug-id-injection/input/bundle2.js, packages/integration-tests/fixtures/debug-id-injection/setup.ts
Since I accidentally broke debug ID generation for esbuild, the time has come to write some tests too...
Writing tests made it obvious that we also don't generate entirely valid debug IDs since the `variant` wasn't correct. This PR also fixes that.
=> fix: Fix esbuild debug ID generation

MIGRATION.md, packages/bundler-plugin-core/package.json, packages/esbuild-plugin/package.json, packages/rollup-plugin/package.json, packages/vite-plugin/package.json, packages/webpack-plugin/package.json
Ref https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/326
The unplugin dependency uses optional chaining which is only available in Node 14 or higher. Additionally, we only run our tests for versions 14 and higher.
=> docs: Update minimum supported Node.js version to 14

packages/bundler-plugin-core/src/utils.ts
Resolves https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/328
I think https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/328 makes a fair point. I originally used the short git sha because I thought it was gonna be prettier on the interface but using the long sha actually has technical upsides:
- Better alignment with Sentry CLI
- Less likely collisions
=> ref: Use full git SHA for release name

packages/bundler-plugin-core/package.json, packages/bundler-plugin-core/src/index.ts, packages/esbuild-plugin/README_TEMPLATE.md, packages/integration-tests/scripts/run-fixture-setups.ts, packages/playground/.gitignore, packages/rollup-plugin/README_TEMPLATE.md, packages/vite-plugin/README_TEMPLATE.md, packages/webpack-plugin/README_TEMPLATE.md, yarn.lock
Resolves https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/332
Adds option to configure environment variables via a `.env.sentry-build-plugin` file inside the cwd.
This is necessary for efforts in https://github.com/getsentry/sentry-wizard/issues/290
=> feat: Add configuration via `.env.sentry-build-plugin` file

packages/bundler-plugin-core/src/types.ts, packages/dev-utils/src/generate-documentation-table.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/338
We previously documented that leaving away the `sourcemaps` option will disable debug ID injection. That is pre v2 behaviour and not the case anymore so we should remove it.
=> docs: Remove misleading documentation

packages/bundler-plugin-core/src/index.ts
This just fixes two tiny typos in some log messages.
=> fix: Fix 'identifiy' typo in log messages

packages/bundler-plugin-core/package.json, yarn.lock
Fixes https://github.com/getsentry/sentry-javascript/issues/8665
=> deps: Bump sentry-cli to 2.20.1 to fix debugid injection issue

packages/bundler-plugin-core/src/debug-id-upload.ts, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/plugins/release-management.ts
Resolves https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/365
=> feat: Allow ommiting `org` when using organization auth token

packages/bundler-plugin-core/src/index.ts
This change will glob for `.js` and `.js.map` files in the defined output folder of rollup and vite instead of relying on the assets provided in the `writeBundle` hook. We assume that this will make the upload a bit more robust in regards to files being missed.
=> ref: Make asset detection more robust

packages/bundler-plugin-core/src/sentry/telemetry.ts
Add options under `_experiments` as tags to the telemetry data.
Closes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/374
=> ref: Add used experiments to telemetry

packages/bundler-plugin-core/src/debug-id-upload.ts
Fixes #375
We have a regex that tries to find the path of a source map of a file via the `//# sourceMappingURL=` comment. It never worked because the this regex was intended to be a multiline regex ... which it wasn't.
This PR turns it into a multiline regex. While we're at it, let's also allow some whitespace in front of the comment.
=> fix: Fix regex in source map locating heuristic via `sourceMappingURL`

packages/bundler-plugin-core/src/debug-id-upload.ts
Attempts to fix https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/352
When there are a lot of source files and source maps we do a lot of moving and modifying concurrently which might take up a lot of memory.
In the case of https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/352 there were 226 source files + source maps which could be a lot, especially when a source map can take up several megabytes of data.
In order not to use as much ram we limit the amount of concurrent preparation jobs to 16. We might see longer compilation times in projects with a lot of output files but we're at least somewhat capping max memory usage.
Probably related: https://github.com/getsentry/sentry-javascript/issues/8805
=> ref: Run upload preparation with maximum concurrency

packages/bundler-plugin-core/src/index.ts, packages/integration-tests/fixtures/metadata-injection/metadata-injection.test.ts, packages/integration-tests/fixtures/metadata-injection/setup.ts, packages/rollup-plugin/src/index.ts, packages/vite-plugin/src/index.ts
Metadata injection has already been added for webpack (#334).
This PR adds this feature for rollup/vite too.
=> feat: Add module metadata injection for vite and rollup

packages/bundler-plugin-core/src/index.ts
We probably do not want to degrade the quality of source maps.
=> ref: Emit high resolution source-maps with `magic-string`

packages/bundler-plugin-core/src/types.ts, packages/esbuild-plugin/src/index.ts, packages/integration-tests/fixtures/metadata-injection/metadata-injection.test.ts, packages/integration-tests/fixtures/metadata-injection/setup.ts
Metadata injection has already been added for webpack (https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/334) and there is an open PR for rollup (#380).
This PR adds this feature for esbuild too which is mostly a copy from `esbuildDebugIdInjectionPlugin`.
My only minor concern is that due to `if (args.kind !== "entry-point") { return }`, it means that code is only injected for entry points. What happens for other chunks that aren't entry, like those created from async import, etc? 
I've done a bit of digging and it appears that esbuild doesn't yet support async import so maybe my concerns can be ignored for now.
=> feat: Add module metadata injection for esbuild

packages/bundler-plugin-core/src/types.ts, packages/dev-utils/src/generate-documentation-table.ts, packages/esbuild-plugin/README_TEMPLATE.md, packages/rollup-plugin/README_TEMPLATE.md, packages/vite-plugin/README_TEMPLATE.md, packages/webpack-plugin/README_TEMPLATE.md
Updates all links that pointed to the user auth token settings page to point to the org auth token settings page instead.
=> docs: Point to org auth token page

MIGRATION.md
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/396
=> docs: Add removal of `dryRun` to migration guide

packages/bundler-plugin-core/src/utils.ts
Fixes #398
By putting the git revision logic into a separate function, we only need to execute git if none of the environment variables exists
=> Move git revision to a separate function

packages/bundler-plugin-core/package.json, yarn.lock
Fix we want to have https://github.com/getsentry/sentry-cli/pull/1766
=> build(core): Bump Sentry CLI to v2.21.2

packages/bundler-plugin-core/src/utils.ts, packages/esbuild-plugin/src/index.ts, packages/integration-tests/fixtures/esbuild-inject-compat/esbuild-inject-compat.test.ts, packages/integration-tests/fixtures/esbuild-inject-compat/input/index.ts, packages/integration-tests/fixtures/esbuild-inject-compat/input/inject.ts, packages/integration-tests/fixtures/esbuild-inject-compat/setup.ts, packages/integration-tests/package.json, yarn.lock
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/413
When `inject` files are defined in esbuild we will inject debug IDs into those files. This means we will have 2+ debug IDs in the output bundles which will potentially mess up our upload logic and debug ID association.
With this PR we skip proxying injected modules therefore only injecting one debug ID per entrypoint (which is the desired outcome).
=> fix(esbuild): Don't inject debug IDs into injected modules

packages/bundler-plugin-core/src/debug-id-upload.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/423
=> fix(core): Don't abort source map location guessing when the reference is a URL

packages/bundler-plugin-core/src/types.ts
Not needed since v7.78.0 of the SDK as there this is excluded by default.
=> feat: deprecate `excludeReplayCanvas` config

packages/bundler-plugin-core/package.json, yarn.lock
we want this fix: https://github.com/getsentry/sentry-cli/pull/1815
thanks.
=> chore: bump @sentry/cli dependency to 2.21.4

packages/bundler-plugin-core/package.json, yarn.lock
Bumps the CLI in order to make use of the new  binaries over npm.
=> deps(core): Bump `@sentry/cli` to `^2.22.3`

packages/bundler-plugin-core/package.json, yarn.lock
Ref: https://github.com/getsentry/sentry-javascript/issues/10121
Ref: https://github.com/getsentry/sentry-javascript/issues/9981#issuecomment-1881151710
We should bundle the SDK dependencies so that we do not facilitate issues with multiple different SDK versions in user's apps.
=> fix: Bundle Sentry SDK dependency

packages/bundler-plugin-core/src/debug-id-upload.ts, packages/bundler-plugin-core/src/plugins/release-management.ts, packages/bundler-plugin-core/src/plugins/telemetry.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/461
I keep forgetting that flushing may throw.
=> fix(core): Safely flush telemetry

packages/babel-plugin-component-annotate/README.md, packages/babel-plugin-component-annotate/src/index.ts, packages/babel-plugin-component-annotate/test/test-plugin.test.ts, packages/bundler-plugin-core/src/index.ts
I know, default exports bad, but we don't have much of a choice here. Babel expects our plugin to be using a default export, or else it will not be able to resolve the plugin when using its string identifier in the config (`@sentry/babel-plugin-component-annotate`)
See this in Babel's source for reference:
https://github.com/babel/babel/blob/main/packages/babel-core/src/config/config-descriptors.ts#L335
=> ref(component-annotate): Use default export

packages/bundler-plugin-core/src/sentry/telemetry.ts
Forgot to port this over from the first PR! Just adds a tag on the transaction so we can track how many users have enabled the react component annotation feature.
In a future PR, I can also look into using Sentry metrics to do this as well, for the sake of 🐶 fooding .
=> feat(core): Add telemetry for React component annotations

packages/bundler-plugin-core/src/index.ts
For some reason `dotenv` is falling back to reading the local `.env` file when the file you actually wanted to read is not present. Obviously this is not what we want so instead we just read it ourselves and just use dotenv to parse it for us.
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/484
=> fix(core): Stop .env files from being picked up

packages/bundler-plugin-core/package.json
As per the sole commit:
> Commit fba3468 pinned `@babel/core` as a dependency. In order to allow users to deduplicate the Babel stack, this commit amends the spec to allow newer versions as well. The same change is made to other 3rd-party production dependencies, except for `unplugin` [1] and `magic-string` [2] which apparently need to be pinned.
[1]: https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/496#issuecomment-1976233741
[2]: https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/496#issuecomment-1976513188
=> Allow newer versions of 3rd-party dependencies of `core`

packages/bundler-plugin-core/src/index.ts
This should not appear every time you run the plugin.
=> ref(annotate): Turn disabled message to debug log

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/types.ts
Adds `_metaOptions` to configure more intimite options for consumption of higher order plugins or build tools.
Adds an option to the meta options (`loggerPrefixOverride`) to allow to configure the prefix for logger messages.
=> feat(core): Add `loggerPrefixOverride` meta option

packages/bundler-plugin-core/src/index.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/508
=> fix: Also match `.cjs` and `.mjs` files when finding files to upload in rollup-based bundlers

packages/bundler-plugin-core/package.json, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/utils.ts, yarn.lock
Attempt to fix https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/512
It seems like we are OOMing users with the plugin. I previously wrote this off as an upstream issue, but looking at the comment https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/379#issuecomment-1714745412 which narrows the OOM issue down to version 2.7.0 or 2.7.1, it seems like https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/383 could have introduced memory issues since `hires: true` will create mappings for every single character.
Now that I am wiser I don't think that is entirely necesary - especially for our use-case. Let's see if removing that option would fix it. It looks like simply removing `hires: true` will drastically reduce the fidelity of source maps …
=> fix: Create word-based fidelity source mapping for code transformations

packages/bundler-plugin-core/src/utils.ts
This PR checks Heroku env vars when trying to determine a release name.
This should align with other Sentry tools (including the Rust cli) and this library also used to support them a very long time ago:
https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/484a719a187fdfdf456b9da1489b8eed1e7dde19/packages/unplugin/src/getReleaseName.ts#L18-L25
Feel free to not add this if this is not wanted!
=> feat: Support Heroku env vars when infering release name

packages/babel-plugin-component-annotate/README.md, packages/esbuild-plugin/README_TEMPLATE.md, packages/rollup-plugin/README_TEMPLATE.md, packages/vite-plugin/README_TEMPLATE.md, packages/webpack-plugin/README_TEMPLATE.md
`pnpm install` is used to install all dependencies for a project, according to the pnpm documentation.
and the appropriate command to install a single package is `pnpm add`. 
- https://pnpm.io/cli/add
- https://pnpm.io/cli/install
=> fix(docs): Update pnpm install commands

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/plugins/release-management.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/src/types.ts, packages/bundler-plugin-core/test/option-mappings.test.ts, packages/bundler-plugin-core/test/sentry/telemetry.test.ts, packages/dev-utils/src/generate-documentation-table.ts, packages/playground/vite.config.smallNodeApp.js
`cleanArtifacts` was historically needed to remove artifacts before uploading to avoid collisions. Since Sentry can nowadays accept multiple artifacts with the same name per release and prefer the most recent one this option is unnecessary.
Additionally, it causes problems like these: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/481  with org auth tokens so moving forward it should noop.
=> feat: Deprecate and noop `cleanArtifacts`

packages/bundler-plugin-core/src/index.ts, packages/esbuild-plugin/src/index.ts
Relates to: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/445#issuecomment-2061371373
=> misc(esbuild): Log warning when attempting to inject debug IDs with esbuild `bundle` option active

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/src/types.ts, packages/bundler-plugin-core/src/utils.ts, packages/integration-tests/fixtures/metadata-injection/setup.ts
Promotes the `moduleMetadata` integration to stable.
=> feat: Promote experimental `moduleMetadata` option to stable

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/types.ts, packages/integration-tests/fixtures/application-key-injection/input/bundle.js, packages/integration-tests/fixtures/application-key-injection/metadata-injection.test.ts, packages/integration-tests/fixtures/application-key-injection/setup.ts
Ties into https://github.com/getsentry/sentry-javascript/pull/12267
Ref https://github.com/getsentry/sentry-javascript/issues/10882
Allows users to mark their bundles with an application key which will allow the SDK to filter events based on application keys in stack frames.
=> feat: Add `applicationKey` option to identify application code from within the SDK

packages/esbuild-plugin/src/index.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/537
In https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/526 we introduced a log message that esbuild's `bundle: true` is not supported. We messed up because it is actually the complete opposite. We don't support `bundle: false`.
This PR flips the logic.
=> fix(esbuild): Invert warning about `bundle: true`

packages/bundler-plugin-core/src/index.ts
This PR fixes an error that occurs when running the "vite" command on some Windows machines (We encountered this issue on 2 out of 5 of our Windows development environments, I'm not sure whats effecting it). The issue and its solution are detailed in https://github.com/vitest-dev/vitest/issues/1870#issuecomment-1501140251 
Applied the fix on affected Windows machines; the error did not reoccur.
Example output of the error;
```
Windows 11
node 22.2.0
vite 5.2.12
@sentry/vite-plugin 2.18.0
node:events:498
throw er; // Unhandled 'error' event
^
Error: spawn undefined\System32\WindowsPowerShell\v1.0\powershell ENOENT
at ChildProcess._handle.onexit (node:internal/child_process:286:19)
at onErrorNT (node:internal/child_process:484:16)
at process.processTicksAndRejections …
```
=> fix(vite): Fix environment variable loading issue for Windows

packages/bundler-plugin-core/src/plugins/telemetry.ts
Refactored a log message in the `telemetry.ts` plugin to improve clarity and reduce false positives when searching for errors in logs.
- packages/bundler-plugin-core/src/plugins/telemetry.ts
The previous log message contained the word "error," which led to confusion when searching for actual errors in the logs using ctrl/cmd + F. The modified message improves the clarity of logs and reduces false positives during searches.
- Improved Log Clarity: The updated log message ensures that searches for "error" in the logs will yield actual error instances rather than telemetry information.
- Reduced False Positives: Developers and users can more easily identify real errors during troubleshooting and debugging sessions.
This change aims to enhance developer experience by streamlining the process …
=> feat: Don't use word "error" in log message about telemetry

packages/bundler-plugin-core/src/debug-id-upload.ts, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/plugins/release-management.ts, packages/bundler-plugin-core/src/plugins/sourcemap-deletion.ts, packages/integration-tests/fixtures/after-upload-deletion/after-upload-deletion.test.ts, packages/integration-tests/fixtures/after-upload-deletion/input/bundle.js, packages/integration-tests/fixtures/after-upload-deletion/setup.ts, packages/integration-tests/utils/create-cjs-bundles.ts
Currently we only delete files when the debug ID upload was initiated. This is extremely confusing if you use the legacy upload or didn't upload at all - for example when not providing an auth token.
With this we will always run deletion when `sourcemaps.filesToDeleteAfterUpload` is set, and up to two additional times, after the debug ID upload and the legacy upload have completed.
=> fix: Always delete files when `sourcemaps.filesToDeleteAfterUpload` is set

packages/esbuild-plugin/src/index.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/554
We tell users in our docs for setting up the esbuild plugin with Angular and Nx to pass the plugin to the plugins array in the Nx config. However, Nx just takes the default export, or if non-existent, whatever is on `module.exports`, as the plugin.
If we export the plugin as default export the issue is fixed.
=> feat: Export esbuild plugin as default

packages/bundler-plugin-core/src/debug-id-upload.ts, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/plugins/release-management.ts, packages/bundler-plugin-core/src/plugins/sourcemap-deletion.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/556
I introduced a dumb bug where we would delete sourcemaps before they have been uploaded due to a race condition.
This PR introduces a sort-of dependency tracking mechanism where we only initiate the file deletions after all the functionalities depending on the files have been completed.
=> fix: Wait for tasks depending on sourcemaps before deleting

packages/bundler-plugin-core/src/sentry/telemetry.ts
This is useful to gauge adoption.
=> feat(telemetry): Collect whether `applicationKey` is set

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/src/types.ts, packages/dev-utils/src/generate-documentation-table.ts
Resolves https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/560
Adds an option `sourcemaps.disable` to completely disable all functionality related to sourcemaps (debug ID process).
=> feat: Add option to disable sourcemaps

packages/bundler-plugin-core/src/plugins/sourcemap-deletion.ts
Sometimes writeBundle is executed before the upload task,  need to ensure the order of code execution
=> fix: Use `sequential` and `post` order for vite artifact deletion

.gitignore, packages/bundler-plugin-core/src/index.ts, packages/playground/vite.config.smallNodeApp.js, packages/vite-plugin/src/index.ts
I didn't really find any good way of testing this so I just relied on manual testing with the user submitted reproduction in https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/552 as well as trying it out in two sample apps, a react app and a solid app which built and uploaded sourcemaps fine.
Closes: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/552
=> fix(vite-plugin): Ensure `post` order of `sentry-vite-release-injection-plugin` to avoid breaking `@rollup/plugin-commonjs` step

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/types.ts, packages/dev-utils/src/generate-documentation-table.ts
Adds an alias because we are rephrasing everything around performance and tracing.
Also adds docs to readme we should have added before.
=> feat: Add `bundleSizeOptimizations.excludeTracing` option as alias to deprecated `bundleSizeOptimizations.excludePerformanceMonitoring`

packages/bundler-plugin-core/src/utils.ts, packages/integration-tests/fixtures/release-value-with-quotes/input/bundle.js, packages/integration-tests/fixtures/release-value-with-quotes/release-value-with-quotes.test.ts, packages/integration-tests/fixtures/release-value-with-quotes/setup.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/584
Properly escapes strings passed as release option.
=> fix: Escape release string in injection snippet

packages/bundler-plugin-core/src/index.ts, packages/integration-tests/fixtures/disabled-debug-id-injection/disabled-debug-id-injection.test.ts, packages/integration-tests/fixtures/disabled-debug-id-injection/input/bundle1.js, packages/integration-tests/fixtures/disabled-debug-id-injection/input/bundle2.js, packages/integration-tests/fixtures/disabled-debug-id-injection/setup.ts
I ran into the case in https://github.com/getsentry/sentry/pull/76051 where it would be super harmful when we injected debug IDs because we later inject debug IDs with the CLI, and the plugin's debug IDs would win, and source maps would break. This is more or less just a reliability patch.
=> fix: Disable debug ID injection when `sourcemaps.disable` is set

packages/bundler-plugin-core/sentry-esbuild-debugid-injection-file.js, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/utils.ts, packages/bundler-plugin-core/test/index.test.ts, packages/bundler-plugin-core/test/utils.test.ts, packages/integration-tests/fixtures/debug-id-injection/debug-id-injection.test.ts, packages/integration-tests/fixtures/metadata-injection/metadata-injection.test.ts
This PR ensures that we always use the `Error` class explicitly from the global object instead of the "ambient" `Error` class. The reason is that users (or as reported frameworks) are free to name their own classes "Error" in which case the file injection would instantiate the user-created and not the global class.
Ref https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/593
=> fix(core): Always instantiate global `Error` class in injected code snippets

packages/bundler-plugin-core/src/debug-id-upload.ts, packages/bundler-plugin-core/src/index.ts, packages/integration-tests/fixtures/injection-with-query-param/injection-with-query-param.test.ts, packages/integration-tests/fixtures/injection-with-query-param/input/bundle1.js, packages/integration-tests/fixtures/injection-with-query-param/input/bundle2.js, packages/integration-tests/fixtures/injection-with-query-param/setup.ts, packages/integration-tests/utils/create-cjs-bundles-with-query.ts, packages/webpack-plugin/src/index.ts
Fixes #596
The previous regex excluded entry points that have query parameters. The common use case for this is content hashes, e.g.:
```js
output: {
filename: "[name].js?contenthash=[contenthash]",
},
```
The new regex will match the same things as before, but additionally allows those filenames to end with a `?` followed by any number of characters. I think this should be fairly safe? The only edge case I can think of is a spacebar heating situation where someone was using the previous behavior to opt out of sentry injection for specific entry points, but that seems unlikely.
=> fix: Allow injection plugins to apply to files with query parameters and fragments in their name

packages/bundler-plugin-core/package.json, yarn.lock
We want to have https://github.com/getsentry/sentry-cli/pull/2143
=> deps: Update `@sentry/cli` to `2.36.1`

packages/bundler-plugin-core/src/utils.ts, packages/bundler-plugin-core/test/utils.test.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/618
=> fix(core): Use sha256 instead of md5 to generate uuids from string

packages/bundler-plugin-core/src/sentry/logger.ts, packages/bundler-plugin-core/test/sentry/logger.test.ts
Resolves: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/551
Switches logger to use `stderr`, not to interfere with `stdout`.
=> chore: Log only to stderr

packages/bundler-plugin-core/src/sentry/telemetry.ts
Will help us better figure out bottlenecks in upload speed.
=> feat(telemetry): Record if plugin is run in CI

packages/bundler-plugin-core/package.json, yarn.lock
We recently had a regression in Sentry CLI that caused uploaded source maps to not be tagged with debug IDs which is mission critical.
Since we cannot allow buggy versions to float around we should pin the version.
=> deps: Bump `@sentry/cli` to `2.39.1` and require specific version

packages/bundler-plugin-core/sentry-esbuild-debugid-injection-file.js, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/utils.ts, packages/bundler-plugin-core/test/index.test.ts, packages/bundler-plugin-core/test/utils.test.ts
Some runtimes like QuickJS only have `globalThis`.
=> feat(core): Write module injections to `globalThis`

packages/bundler-plugin-core/src/utils.ts
This change adds release name detection for Railway
Based on https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/549
Related: https://github.com/getsentry/sentry-javascript/pull/14691
=> feat(core): Detect Railway release name

packages/bundler-plugin-core/src/plugins/release-management.ts, packages/esbuild-plugin/test/public-api.test.ts, packages/rollup-plugin/test/public-api.test.ts, packages/vite-plugin/test/public-api.test.ts, packages/webpack-plugin/test/public-api.test.ts
- Renames the release management plugin name from `sentry-debug-id-upload-plugin` to `sentry-release-management-plugin`
- adds simple tests to catch renamings/regressions since they have a potential effect on SDKs like `@sentry/sveltekit`
=> ref(core): Rename release management plugin name

packages/bundler-plugin-core/src/index.ts, packages/webpack-plugin/src/index.ts
This PR is heavily inspired by https://github.com/unjs/unplugin/issues/323#issuecomment-2208626770 where the suggestion is made to exit the process in the `done` hook of the webpack compiler. We have multiple reports of our webpack plugin stalling angular builds. This came up again recently so I thought we could give this fix a try.
Full disclosure: I cannot reproduce the stall posted in https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/345, but from my limited local testing, this at least doesn't seem to break anything. However, exiting the process is still scary, so not sure if we should really do it. I guess with TanStack, there's at least precedence for this.
Reviewers - WDYT?
=> fix(webpack): Ensure process exits when done

CHANGELOG.md, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/src/types.ts, packages/integration-tests/fixtures/bundle-size-optimizations/setup.ts
- Ref #651
Do you want to remove `injectBuildInformation` from `_experiments` too? It hasn't been deprecated yet 🤔
=> chore: Remove deprecated options and update changelog for v3 major

packages/bundler-plugin-core/src/utils.ts, packages/bundler-plugin-core/test/utils.test.ts
=> fix!: Wrap injected code in block-statement to contain scope

packages/bundler-plugin-core/sentry-esbuild-debugid-injection-file.js, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/utils.ts, packages/bundler-plugin-core/test/index.test.ts, packages/bundler-plugin-core/test/utils.test.ts
Reverts getsentry/sentry-javascript-bundler-plugins#610
See https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/610#issuecomment-2591919621 as to why.
=> Revert "feat(core)!: Use `globalThis` for code injection"

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/types.ts, packages/webpack-plugin/src/index.ts
In #653 I introduced a forced process exit when the webpack build was done. This turned out to happen too early in NextJS builds. My guess is that there are multiple builds in the same process, meaning that we'd exit when the first one is done. This PR now reverts the default behaviour to no longer exit the process. Instead, users can set an experimental flag to force exiting the process (e.g. for https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/345):
```js
sentryWebpackPlugin({
// ...other options
_experiments: { forceExitOnBuildCompletion: true },
});
```
Given we received no confirmation that this actually solves #345 so far, I think keeping this experimental for now is the best option.
fixes #662 
probably also addresses …
=> feat(webpack): Gate forced process exit behind experimental flag

packages/bundler-plugin-core/src/index.ts, packages/rollup-plugin/test/public-api.test.ts, packages/vite-plugin/test/public-api.test.ts
perfect PR id 😈 
This PR improves the check for if the plugin is called in dev/watch mode or for a production build. In case of the former, we return a no-op plugin. This was already the [expected behaviour](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/vite/#configuration) previously but due to the unplugin meta context only holding the `watchmode` flag in theory but not in practise, we'd always return the actual plugins.
This should also remove the log output in dev mode.
closes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/344
probably also closes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/520 (I'll leave a reply to get confirmation)
cc @cleptric
=> fix(core): Check for dev mode via `process.env.NODE_ENV`

packages/bundler-plugin-core/src/plugins/sourcemap-deletion.ts, packages/bundler-plugin-core/src/types.ts, packages/dev-utils/src/generate-documentation-table.ts, packages/integration-tests/fixtures/after-upload-deletion-promise/after-upload-deletion.test.ts, packages/integration-tests/fixtures/after-upload-deletion-promise/input/bundle.js, packages/integration-tests/fixtures/after-upload-deletion-promise/setup.ts
Some framework SDKs require us to lazily set a "fallback" `filesToDeleteAfterSourcemaps` option that we don't yet know at plugin creation time. This PR widens the accepted type for `filesToDeleteAfterSourcemaps` to also allow us (as well as users) to pass in a `Promise<string | string[]>` to do so. This promise can resolve whenever we know what to set.
Necessary for SvelteKit 
ref https://github.com/getsentry/sentry-javascript/issues/15414
=> feat(core): Accept and await a promise in `sourcemaps.filesToDeleteAfterUpload`

README.md
The docs for RCN point to this plugin, so adding that functionality to the list of features
=> docs: Add react component name to feature list

packages/bundler-plugin-core/src/index.ts
=> chore: Suggest putting `SENTRY_AUTH_TOKEN`, `SENTRY_ORG` and `SENTRY_PROJECT` in `passThroughEnv` when using Turborepo

packages/babel-plugin-component-annotate/src/index.ts, packages/babel-plugin-component-annotate/test/__snapshots__/test-plugin.test.ts.snap, packages/babel-plugin-component-annotate/test/test-plugin.test.ts
This pr adds functionality for ignoring components like `Tab.Group` which are commonly used e.g. in HeadlessUI.
closes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/686
=> feat(annotation): Handle JSX member expressions

packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/plugins/release-management.ts, packages/bundler-plugin-core/src/types.ts, packages/bundler-plugin-core/test/option-mappings.test.ts, packages/dev-utils/src/generate-documentation-table.ts, packages/integration-tests/fixtures/telemetry/telemetry.test.ts
It's just way better UX if we default to automatically setting commits on releases if Sentry CLI is able to detect them.
We just have to jump through some hoops to not throw by default but throw if people manually configured stuff.
=> feat: Default to automatically setting commits on release

packages/bundler-plugin-core/src/index.ts
=> typo: Turborepo instead of TruboRepo

packages/dev-utils/src/generate-documentation-table.ts
Adds a small disclaimer in the docs of the `reactComponentAnnotation` option stating the risks of using it.
=> docs: Warn about risks of `reactComponentAnnotation`

packages/webpack-plugin/src/index.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/15745
It seems like this hash is more consistent across CPU architectures.
=> feat(webpack): Primarily use `contentHash` for debug ID hash

packages/bundler-plugin-core/src/debug-id-upload.ts
This PR changes our "upload preparation" logic in the debug ID upload to not emit files named after their debug IDs, but rather after their actual file-names.
Files that would have previously been uploaded as `~/0-96b0eb2b-013a-5640-8ffc-4fd8465bb570.js` would now be uploaded as `~/0/out/rollup/entrypoint1.mjs` which is slightly easier to debug.
We still need to do some kind of collision-prevention in case two files are named identically relative to cwd after normalization, so that's why there's still a `/{number}` prefix in the artifact name (it is the "bundle index" which is an incrementing counter).
=> feat(core): Use path instead of debug IDs as artifact names for debug ID upload

CHANGELOG.md, packages/bundler-plugin-core/src/debug-id-upload.ts
This reverts commit e7251f88aa37088b7f58abd9268359c1888a66e6.
It caused a bunch of problems leading to sourcemaps not being uploaded in nextjs.
=> Revert "feat(core): Use path instead of debug IDs as artifact names for debug ID upload (#700)"

packages/bundler-plugin-core/src/options-mapping.ts
Just noticed this is extremely spammy when you have your git email connected with Sentry.
=> feat: Only do automatic commit association for Vercel production environments

CHANGELOG.md, packages/webpack-plugin/rollup.config.js
=> fix(webpack5): Ensure all `esm` files have `.mjs` postfix

.github/workflows/checks.yml, packages/integration-tests/fixtures/disabled-debug-id-injection/disabled-debug-id-injection.test.ts, packages/integration-tests/package.json, packages/integration-tests/utils/create-cjs-bundles.ts, yarn.lock
- Closes #723
This PR:
- Adds Node v20 and v22 to the CI test matrix (We now test 14-22)
- Adds Vite v6 and Rollup v4 to the tests and ensures they're only imported andrun on Node versions that support them
=> test: More bundler versions

packages/integration-tests/package.json, packages/integration-tests/utils/create-cjs-bundles.ts, yarn.lock
This PR reverts #725 because:
- I broke the `NODE_MAJOR_VERSION` code and it was ending up as `NaN` due to the leading `v`
- No tests were actually checking the rollup4 or vite6 output
Now I'm testing Vite 6 in this configuration, it does not work. It resolves `rollup` to `rollup@3` whereas it needs `rollup@4`. I think we can only test these vastly different versions with multiple `node_modules` install directories and a different approach.
=> revert: Testing additional bundlers

package.json, scripts/get-commit-list.ts, yarn.lock
Adds the same `yarn changelog` script as in the `sentry-javascript` repo to extract a pre-formatted commit list we can easily insert into our CHANGELOG entries. Trialed in #743
=> chore: Add changelog generation script

packages/babel-plugin-component-annotate/src/index.ts, packages/bundler-plugin-core/src/build-plugin-manager.ts, packages/bundler-plugin-core/src/debug-id-upload.ts, packages/bundler-plugin-core/src/index.ts, packages/bundler-plugin-core/src/sentry/telemetry.ts, packages/bundler-plugin-core/src/sentry/transports.ts, packages/bundler-plugin-core/src/utils.ts, packages/bundler-plugin-core/test/utils.test.ts, packages/e2e-tests/.eslintrc.js, packages/eslint-configs/base.js, packages/integration-tests/.eslintrc.js, packages/vite-plugin/src/index.ts
This PR turns on the `explicit-function-return-type` eslint rule. I noticed in #741 that we tended to export public API with implicit function return types (and sometimes even declared types dynamically from implicit function return types). This has high potential to introduce accidental breaking changes. While I rewrote the biggest offenders in #741, this PR now turns on an eslint rule to enforce explicit function return types. 
As a result of the eslint rule, I had to turn add some return types but most of them are very straight forward. I'll leave comments on things that need special attention.
=> ref: Enable `explicit-function-return-type` eslint rule

packages/bundler-plugin-core/src/build-plugin-manager.ts, packages/integration-tests/fixtures/debug-ids-already-injected/input/rollup4/rollup.config.js, packages/integration-tests/fixtures/debug-ids-already-injected/input/vite6/vite.config.js, packages/integration-tests/fixtures/debug-ids-already-injected/input/webpack5/webpack.config.js
This bugged me and many users for a while: Because of a weird control flow in the debugID source maps upload plugin, we'd print the "Successfully uploaded source maps to Sentry" message if
- a bunch of important preconditions for uploading were not met (e.g. missing auth token). 
- I think this was actually a pretty bad bug because it would cause Sentry CLI to do validation when it was called although we could have avoided this entirely.
- we didn't upload anything (i.e. we found 0 assets)
This PR fixes both cases.
closes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/670
=> fix(core): Avoid showing success message if upload was disabled or nothing was uploaded

packages/babel-plugin-component-annotate/package.json, packages/bundler-plugin-core/package.json, packages/esbuild-plugin/package.json, packages/rollup-plugin/package.json, packages/vite-plugin/package.json, packages/webpack-plugin/package.json
Release 2.23.1 was marked as `latest` on NPM. We're already releasing a new 4.0.2 release, to ensure that `latest` again points to 4.x. 
However, for the next time, this PR ensures we directly assign the `v2` tag instead of `latest` (see https://github.com/getsentry/sentry-javascript/pull/12047 in the JS SDK repo)
oh, also:
=> chore: Set `v2` NPM tag when publishing v2 releases

packages/bundler-plugin-core/src/build-plugin-manager.ts
Closes #796 
- Problem: The `headers` option is ignored in the `sentryWebpackPlugin`.
- Solution: Pass `options.headers` to `SentryCli` in `createCliInstance` method.
- Impact: Enables use of custom custom headers
=> fix(webpack-plugin): forward headers option to sentry-cli

packages/bundler-plugin-core/src/build-plugin-manager.ts, packages/bundler-plugin-core/test/build-plugin-manager.test.ts
This PR does a few things related to source map uploads without preparing artifacts:
- When `prepareArtifacts` is set to `false` we previously still used glob for finding upload assets. Since these were passed directly to the CLI without moving them to a temp folder before this led to a one-request-per-asset situation which we want to avoid. Now with this change we just pass the build artifacts path directly CLI, which will handle gathering the files to upload and batching them more efficiently.
- Emits a log when custom assets are provided and `prepareArtifacts` is set to `false` since this will be passed to the cli directly as well.
- Early return when an empty assets array was provided.
=> feat(core): No asset globbing for direct upload

packages/bundler-plugin-core/src/options-mapping.ts, packages/bundler-plugin-core/src/types.ts, packages/bundler-plugin-core/test/option-mappings.test.ts, packages/dev-utils/src/generate-documentation-table.ts
Setting `release: { deploy: false }` now opts out of automatic deploy creation (currently done only for Vercel).
Closes: #799
=> feat(core): Extend deploy option to allow opting out of automatic deploy creation
