getsentry/sentry-javascript-bundler-plugins

- packages/bundler-plugin-core/src/detect-release.ts
- packages/bundler-plugin-core/src/index.ts
- packages/bundler-plugin-core/src/options-mapping.ts
- packages/bundler-plugin-core/src/sentry/releasePipeline.ts
- packages/bundler-plugin-core/src/types.ts
- packages/bundler-plugin-core/test/getReleaseName.test.ts
- packages/bundler-plugin-core/test/option-mappings.test.ts
- packages/bundler-plugin-core/types.tsconfig.json
This PR adds normalization of user options that should make it easier to work with them down the line.
> ref: Normalize user options

- packages/bundler-plugin-core/src/options-mapping.ts
- packages/bundler-plugin-core/src/sentry/releasePipeline.ts
- packages/bundler-plugin-core/src/sentry/sourcemaps.ts
- packages/bundler-plugin-core/test/option-mappings.test.ts
> ref: Clean up `include` logic

- .github/workflows/checks.yml
- package.json
- packages/bundler-plugin-core/package.json
- packages/e2e-tests/package.json
- packages/esbuild-plugin/package.json
- packages/eslint-configs/package.json
- packages/integration-tests/package.json
- packages/playground/package.json
- packages/rollup-plugin/package.json
- packages/vite-plugin/package.json
- packages/webpack-plugin/package.json
Ensure node & yarn are consistent.
Also add a node engine to all (potential) public packages (I set it to node >= 10??)
> chore: Setup volta

- packages/bundler-plugin-core/src/index.ts
- packages/bundler-plugin-core/src/options-mapping.ts
- packages/bundler-plugin-core/src/sentry/telemetry.ts
- packages/bundler-plugin-core/src/types.ts
This PR just cleans up some code, left-over TODOs and adds a few JSDoc improvements
> chore(core): Cleanup code and JSDocs

- packages/bundler-plugin-core/src/index.ts
Fixes release injection for Vite on Windows.
> fix(core): Normalize `id` and `releaseInjectionTargets` in `transformInclude`

- .github/workflows/codeql.yml
This is a security requirement iirc - adding this. See: https://www.notion.so/sentry/Security-Transparency-Page-7e9937fcad3b41bd985c352ee2e10664#d584389ccb9d463b9c001f0c40915f70
> build: Add CodeQL scanning

- .craft.yml
- CHANGELOG.md
- packages/webpack-plugin/package.json
This PR enables publishing of the `@sentry/webpack-plugin` package from this repository.
> build(webpack): Publish `@sentry/webpack-plugin`

- CHANGELOG.md
- packages/webpack-plugin/package.json
Something always just has to go wrong...
> build(webpack): Add `build:npm` command

- .github/workflows/checks.yml
Volta keeps flaking and rate-limiting :(
> ci: Use setup-node instead of volta

- .github/workflows/checks.yml
> ci: Skip E2E tests

- .craft.yml
- packages/webpack-plugin/package.json
Configures the package.json and craft instructions to also release the webpack plugin.
> build(webpack): Publish webpack plugin on release action

- .yarnrc
- yarn.lock
Yarn registry is super flakey and times out all the time in CI let's see if this fixes the problem.
> meta: Use npm registry

- .github/workflows/checks.yml
- .gitignore
- .prettierignore
- lerna.json
- nx.json
- package.json
- yarn.lock
> ci: Use Nx cache

- packages/bundler-plugin-core/src/index.ts
- packages/bundler-plugin-core/src/utils.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/260
> fix(core): Ignore query and hash in filepaths for release injection

- packages/e2e-tests/package.json
- packages/e2e-tests/utils/create-cjs-bundles.ts
- packages/integration-tests/fixtures/build-information-injection/build-information-injection.test.ts
- packages/integration-tests/package.json
- packages/integration-tests/utils/create-cjs-bundles.ts
- packages/playground/build-webpack5.js
- packages/playground/package.json
- packages/webpack-plugin/package.json
- packages/webpack-plugin/rollup.config.js
- packages/webpack-plugin/src/index.ts
- yarn.lock
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/255
> ref(webpack): Use webpack peer dependency

- packages/webpack-plugin/package.json
Found problem in https://stackoverflow.com/a/76319670/21967320
> fix(webpack): Set minimum webpack 4 peer dep to `4.40.0`

- packages/bundler-plugin-core/src/debug-id-upload.ts
> feat: Log upon successful upload

- packages/bundler-plugin-core/src/types.ts
- packages/dev-utils/src/generate-documentation-table.ts
Just amending a typo nothing biggie, hopefully I did everything correct.
> docs: Fix typo

- packages/vite-plugin/README_TEMPLATE.md
Fixed invalid option for pnpm installation of vite plugin.
> Update instructions to install Vite plugin - README_TEMPLATE.md

- packages/bundler-plugin-core/package.json
- yarn.lock
Resolves https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/349
> deps: Bump and unpin Sentry SDK deps

- packages/webpack-plugin/src/index.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/394
> fix(webpack): Add `default` fallback to webpack import

- packages/bundler-plugin-core/src/types.ts
- packages/dev-utils/src/generate-documentation-table.ts
small tweak to fix typo in the docs.
> docs: Fix "latter requires" typo

- .github/workflows/checks.yml
- .github/workflows/codeql.yml
- .github/workflows/release.yml
Bumps actions from node 16 to 20
> deps(ci): Bump actions

- README.md
ref https://github.com/getsentry/team-sdks/issues/87
> chore: Add contributors to README

- .github/workflows/checks.yml
Committed via https://github.com/asottile/all-repos
> ci: Update actions/upload-artifact to v4

- packages/bundler-plugin-core/package.json
- yarn.lock
> deps: Bump `@sentry/cli` to `2.41.1`

- CHANGELOG.md
Includes:
- **feat(core): Accept and await a promise in `sourcemaps.filesToDeleteAfterUpload` (#677)**
Oh, also:
> meta: Update changelog for 3.2.0

- CHANGELOG.md
> meta: Update Changelog for 3.2.2

- CHANGELOG.md
Let's get #763 out so that we can cut the major afterwards
> meta: Update changelog for 3.6.1

- CHANGELOG.md
> meta: Changelog entry for 4.1.1

- CHANGELOG.md
4.2.0 release was retracted so including one more fix here
> meta: Update changelog entry for 4.2.0
